from enum import IntEnum


MAIN_MENU = "В главное меню"


class Button(IntEnum):
    TRAINS = 0
    STATISTIC = 1
    SET_TRAINS = 2

    CHANGE_EXERCISE = 10
    CHANGE_TRAIN_NAME = 11
    ADD_EXERCISE = 12
    BACK_TO_TRAIN = 13

    DELETE_EXERCISE = 20
    RENAME_EXERCISE = 21
    CHANGE_SETTINGS_EXERCISE = 22
    BACK_TO_EXERCISE = 23

    DELETE_TRAIN = 30
    CREATE_TRAIN = 31
    CHANGE_TRAIN = 32



